postgres_medallion:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5434
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'medallion_db') }}"
      schema: public
      threads: 4
      keepalives_idle: 0

    prod:
      type: postgres
      host: localhost
      port: 5434
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'medallion_db') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
