version: 2

sources:
  - name: raw_data
    description: "Raw data source - could be from external systems, APIs, or file uploads"
    schema: bronze
    tables:
      - name: raw_customers
        description: "Raw customer data"
        columns:
          - name: customer_id
            description: "Unique customer identifier"
            tests:
              - not_null
          - name: customer_name
            description: "Customer name"
          - name: email
            description: "Customer email"
          - name: created_at
            description: "Record creation timestamp"

      - name: raw_orders
        description: "Raw order data"
        columns:
          - name: order_id
            description: "Unique order identifier"
            tests:
              - not_null
          - name: customer_id
            description: "Customer who placed the order"
          - name: order_date
            description: "Order date"
          - name: amount
            description: "Order amount"

      - name: raw_products
        description: "Raw product catalog data"
        columns:
          - name: product_id
            description: "Unique product identifier"
            tests:
              - not_null
              - unique
          - name: product_name
            description: "Product name"
          - name: category
            description: "Product category"
          - name: subcategory
            description: "Product subcategory"
          - name: price
            description: "Retail price"
          - name: cost
            description: "Cost of goods sold"
          - name: supplier
            description: "Supplier name"
          - name: sku
            description: "Stock keeping unit"
          - name: created_at
            description: "Product creation timestamp"
          - name: updated_at
            description: "Last update timestamp"

      - name: raw_payments
        description: "Raw payment transaction data"
        columns:
          - name: payment_id
            description: "Unique payment identifier"
            tests:
              - not_null
              - unique
          - name: order_id
            description: "Associated order ID"
            tests:
              - not_null
          - name: payment_method
            description: "Payment method (credit_card, debit_card, paypal, etc.)"
          - name: payment_status
            description: "Payment status (completed, pending, failed, refunded)"
          - name: transaction_amount
            description: "Transaction amount"
          - name: processing_fee
            description: "Payment processing fee"
          - name: gateway
            description: "Payment gateway (Stripe, PayPal, Square)"
          - name: card_last_four
            description: "Last 4 digits of card (if applicable)"
          - name: processed_at
            description: "Payment processing timestamp"
          - name: updated_at
            description: "Last update timestamp"

      - name: raw_customer_events
        description: "Raw customer behavioral event data"
        columns:
          - name: event_id
            description: "Unique event identifier"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Customer who triggered the event"
          - name: event_type
            description: "Type of event (page_view, product_view, add_to_cart, purchase, etc.)"
          - name: event_category
            description: "Event category (navigation, engagement, conversion)"
          - name: page_url
            description: "URL where event occurred"
          - name: session_id
            description: "Session identifier"
          - name: device_type
            description: "Device type (desktop, mobile, tablet)"
          - name: browser
            description: "Browser used"
          - name: event_timestamp
            description: "Event timestamp"
          - name: created_at
            description: "Record creation timestamp"

      - name: raw_stores
        description: "Raw store location data"
        columns:
          - name: store_id
            description: "Unique store identifier"
            tests:
              - not_null
              - unique
          - name: store_name
            description: "Store name"
          - name: store_type
            description: "Store type (flagship, standard, outlet)"
          - name: address
            description: "Street address"
          - name: city
            description: "City"
          - name: state
            description: "State"
          - name: country
            description: "Country"
          - name: postal_code
            description: "Postal code"
          - name: phone
            description: "Store phone number"
          - name: manager_name
            description: "Store manager name"
          - name: opened_at
            description: "Store opening date"
          - name: updated_at
            description: "Last update timestamp"

      - name: raw_inventory
        description: "Raw inventory level data"
        columns:
          - name: inventory_id
            description: "Unique inventory record identifier"
            tests:
              - not_null
              - unique
          - name: product_id
            description: "Product identifier"
            tests:
              - not_null
          - name: store_id
            description: "Store identifier"
            tests:
              - not_null
          - name: quantity_on_hand
            description: "Current quantity available"
          - name: reorder_point
            description: "Quantity threshold for reordering"
          - name: reorder_quantity
            description: "Quantity to order when restocking"
          - name: last_restocked_at
            description: "Last restock timestamp"
          - name: updated_at
            description: "Last update timestamp"

      - name: raw_order_items
        description: "Raw order line item data linking orders to products"
        columns:
          - name: order_item_id
            description: "Unique order item identifier"
            tests:
              - not_null
              - unique
          - name: order_id
            description: "Associated order ID"
            tests:
              - not_null
          - name: product_id
            description: "Associated product ID"
            tests:
              - not_null
          - name: quantity
            description: "Quantity ordered"
          - name: unit_price
            description: "Price per unit at time of order"
          - name: discount
            description: "Discount amount applied"
          - name: line_total
            description: "Total for this line item (quantity * unit_price - discount)"

models:
  - name: bronze_customers
    description: "Bronze layer - Raw customer data with minimal transformation"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Customer name"
      - name: email
        description: "Customer email"
      - name: created_at
        description: "Record creation timestamp"
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"

  - name: bronze_orders
    description: "Bronze layer - Raw order data with minimal transformation"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer who placed the order"
      - name: order_date
        description: "Order date"
      - name: amount
        description: "Order amount"
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"

  - name: bronze_products
    description: "Bronze layer - Raw product data with minimal transformation"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
      - name: category
        description: "Product category"
      - name: subcategory
        description: "Product subcategory"
      - name: price
        description: "Retail price"
      - name: cost
        description: "Cost of goods sold"
      - name: supplier
        description: "Supplier name"
      - name: sku
        description: "Stock keeping unit"
      - name: created_at
        description: "Product creation timestamp"
      - name: updated_at
        description: "Last update timestamp"
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"

  - name: bronze_payments
    description: "Bronze layer - Raw payment data with minimal transformation"
    columns:
      - name: payment_id
        description: "Unique payment identifier"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Associated order ID"
      - name: payment_method
        description: "Payment method"
      - name: payment_status
        description: "Payment status"
      - name: transaction_amount
        description: "Transaction amount"
      - name: processing_fee
        description: "Payment processing fee"
      - name: gateway
        description: "Payment gateway"
      - name: card_last_four
        description: "Last 4 digits of card"
      - name: processed_at
        description: "Payment processing timestamp"
      - name: updated_at
        description: "Last update timestamp"
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"

  - name: bronze_customer_events
    description: "Bronze layer - Raw customer event data with minimal transformation"
    columns:
      - name: event_id
        description: "Unique event identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer who triggered the event"
      - name: event_type
        description: "Type of event"
      - name: event_category
        description: "Event category"
      - name: page_url
        description: "URL where event occurred"
      - name: session_id
        description: "Session identifier"
      - name: device_type
        description: "Device type"
      - name: browser
        description: "Browser used"
      - name: event_timestamp
        description: "Event timestamp"
      - name: created_at
        description: "Record creation timestamp"
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"

  - name: bronze_stores
    description: "Bronze layer - Raw store data with minimal transformation"
    columns:
      - name: store_id
        description: "Unique store identifier"
        tests:
          - unique
          - not_null
      - name: store_name
        description: "Store name"
      - name: store_type
        description: "Store type"
      - name: address
        description: "Street address"
      - name: city
        description: "City"
      - name: state
        description: "State"
      - name: country
        description: "Country"
      - name: postal_code
        description: "Postal code"
      - name: phone
        description: "Store phone number"
      - name: manager_name
        description: "Store manager name"
      - name: opened_at
        description: "Store opening date"
      - name: updated_at
        description: "Last update timestamp"
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"

  - name: bronze_inventory
    description: "Bronze layer - Raw inventory data with minimal transformation"
    columns:
      - name: inventory_id
        description: "Unique inventory record identifier"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Product identifier"
      - name: store_id
        description: "Store identifier"
      - name: quantity_on_hand
        description: "Current quantity available"
      - name: reorder_point
        description: "Quantity threshold for reordering"
      - name: reorder_quantity
        description: "Quantity to order when restocking"
      - name: last_restocked_at
        description: "Last restock timestamp"
      - name: updated_at
        description: "Last update timestamp"
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"

  - name: bronze_order_items
    description: "Bronze layer - Raw order line item data with minimal transformation"
    columns:
      - name: order_item_id
        description: "Unique order item identifier"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Associated order ID"
        tests:
          - not_null
      - name: product_id
        description: "Associated product ID"
        tests:
          - not_null
      - name: quantity
        description: "Quantity ordered"
        tests:
          - not_null
      - name: unit_price
        description: "Price per unit at time of order"
        tests:
          - not_null
      - name: discount
        description: "Discount amount applied"
      - name: line_total
        description: "Total for this line item"
        tests:
          - not_null
      - name: loaded_at
        description: "Timestamp when data was loaded into bronze layer"
